apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finance-api
  template:
    metadata:
      labels:
        app: finance-api
    spec:
      containers:
      - name: finance-api
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.image.port }}
        env:
        - name: POSTGRES_USER
          value: "finance_user"
        - name: POSTGRES_PASSWORD
          value: "strongpassword"
        - name: POSTGRES_DB
          value: "finance_db"
        - name: POSTGRES_HOST
          value: "finance-db-postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)"
        - name: SIMPLEFIN_ACCESS_URL
          value: "https://F562041B71F6D6068C6F3B70CF80CBFA19C526DE7672C7F79DEBC1215257CCA7:CB73104D9BB773301EA1BB995360E2E1FAB6FA772A8C4CD1F3DB2C3FA6C33446@beta-bridge.simplefin.org/simplefin"
        